/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
module

public import Mathlib.CategoryTheory.MorphismProperty.Comma
public import Mathlib.CategoryTheory.Sites.MorphismProperty
public import Mathlib.CategoryTheory.Sites.Over

/-!

# Sites on `P.Over ⊤ X`

We provide some API for proving properties of `P.Over ⊤ X` in relation to precoverages. Consider
a precoverage `K` on `C`.

## Main results

- `CategoryTheory.MorphismProperty.locallyCoverDense_forget_of_le`:
  The forgetful functor `P.Over ⊤ X ⥤ Over X` is locally cover dense if morphisms in `K`
  satisfy `P`.
- `CategoryTheory.MorphismProperty.toGrothendieck_comap_forget_eq_inducedTopology`: The topology
  generated by the precoverage induced from `K` via the composition `P.Over ⊤ X ⥤ Over X ⥤ C` is
  the induced topology from the forgetful functor `P.Over ⊤ X ⥤ Over X`.

-/

@[expose] public section

universe v u

open CategoryTheory MorphismProperty Limits

namespace CategoryTheory.MorphismProperty

variable {C : Type*} [Category* C]

variable {P : MorphismProperty C} {S : C} [P.IsStableUnderComposition]

set_option backward.isDefEq.respectTransparency false in
lemma exists_map_eq_of_presieve (K : Precoverage C) (H : K ≤ P.precoverage)
    {X : P.Over ⊤ S} {R : Presieve ((MorphismProperty.Over.forget P ⊤ S).obj X)}
    (hR : R ∈ (K.comap <| CategoryTheory.Over.forget S) _) :
    ∃ T : Presieve X, T.map (MorphismProperty.Over.forget P ⊤ S) = R := by
  refine ⟨R.functorPullback (MorphismProperty.Over.forget P ⊤ S), le_antisymm (Presieve.map_functorPullback _) ?_⟩
  intro Y f hf
  let Y' : P.Over ⊤ S := Over.mk ⊤ Y.hom (by
    rw [← CategoryTheory.Over.w f]; exact P.comp_mem _ _ (H _ hR (.of hf)) X.prop)
  exact .of (u := (Over.homMk f.left (by simp [Y']) trivial : Y' ⟶ X)) hf

variable (K : Precoverage C) [K.HasIsos] [K.IsStableUnderBaseChange] [K.IsStableUnderComposition]
  [K.HasPullbacks]

lemma locallyCoverDense_forget_of_le (H : K ≤ P.precoverage) :
    (MorphismProperty.Over.forget P ⊤ S).LocallyCoverDense (K.toGrothendieck.over S) := by
  rw [over_toGrothendieck_eq_toGrothendieck_comap_forget]
  apply Precoverage.locallyCoverDense_of_map_functorPullback_mem
  intro X R hR
  obtain ⟨R, rfl⟩ := MorphismProperty.exists_map_eq_of_presieve _ H hR
  simpa

lemma toGrothendieck_comap_forget_eq_inducedTopology
    (H : K ≤ P.precoverage) :
    haveI := MorphismProperty.locallyCoverDense_forget_of_le (S := S) K H
    (K.comap (MorphismProperty.Over.forget P ⊤ _ ⋙ CategoryTheory.Over.forget S)).toGrothendieck =
      (MorphismProperty.Over.forget P ⊤ _).inducedTopology (K.toGrothendieck.over S) := by
  rw [Precoverage.comap_comp]
  simp_rw [over_toGrothendieck_eq_toGrothendieck_comap_forget]
  apply Precoverage.toGrothendieck_comap_eq_inducedTopology
  intro X R hR
  obtain ⟨T, rfl⟩ := MorphismProperty.exists_map_eq_of_presieve K H hR
  simpa

end CategoryTheory.MorphismProperty
